---
# Step 1: Inventory Setup on localhost
- name: SLES Linux OS Patching - Inventory Setup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Define a list of new hosts with their groups and credentials
      set_fact:
        new_hosts:
          - hostname: 10.255.154.216
            group: servers
            ansible_user: admin01
            ansible_ssh_pass: admin@123
            ansible_become_pass: admin@123

    - name: Add new hosts to inventory
      add_host:
        name: "{{ item.hostname }}"
        groups: "{{ item.group }}"
        ansible_user: "{{ item.ansible_user }}"
        ansible_ssh_pass: "{{ item.ansible_ssh_pass }}"
        ansible_become_pass: "{{ item.ansible_become_pass }}"
      loop: "{{ new_hosts }}"

    - name: Display the new hosts added to the inventory
      debug:
        msg: "Added host: {{ item.hostname }} to group: {{ item.group }}"
      loop: "{{ new_hosts }}"

# Step 2: Run Patching Tasks on Added Hosts
- name: Run commands on multiple servers with sudo privileges
  hosts: servers
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
    - name: Check for available updates on remote servers using zypper
      command: yum repolist all
      register: update_list
      become: yes  # Run with sudo on the target servers
      delegate_to: localhost

    - name: Display raw update list from remote servers
      debug:
        msg: "{{ update_list.stdout }}"
      delegate_to: localhost

    - name: Check if no updates were found
      debug:
        msg: "No updates available"
      when: "'No updates found' in update_list.stdout"
      delegate_to: localhost

    - name: Display available updates
      debug:
        msg: "Updates available: {{ update_list.stdout }}"
      when: "'No updates found' not in update_list.stdout"
      delegate_to: localhost
